# Generated by Django 4.2.7 on 2025-05-26 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название книги')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_ru', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('author_ky', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Изображение книги')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/', verbose_name='Файл книги')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('read_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['id'],
            },
        ),
    ]
