# Generated by Django 4.2.7 on 2025-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
