# Generated by Django 4.2.7 on 2025-05-26 11:09

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='american_corner/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Американский уголок',
                'verbose_name_plural': 'Американские уголки',
            },
        ),
        migrations.CreateModel(
            name='MainProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название основного проекта')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название основного проекта')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название основного проекта')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание основного проекта')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание основного проекта')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание основного проекта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_projects/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Основной проект',
                'verbose_name_plural': 'Основные проекты',
            },
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта (Кыргызский)')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание проекта (Кыргызский)')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание проекта (Кыргызский)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_projects/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('title_2', models.CharField(max_length=255, verbose_name='основыные проекты')),
                ('title_2_ru', models.CharField(max_length=255, null=True, verbose_name='основыные проекты')),
                ('title_2_ky', models.CharField(max_length=255, null=True, verbose_name='основыные проекты')),
            ],
            options={
                'verbose_name': 'Наш проект',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
