# Generated by Django 4.2.7 on 2025-05-26 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Объявление о мероприятиях', max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(help_text='Объявление о мероприятиях', max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(help_text='Объявление о мероприятиях', max_length=255, null=True, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='afisha/', verbose_name='Изображение')),
                ('description', ckeditor.fields.RichTextField(help_text='Описание библиотеки', verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(help_text='Описание библиотеки', null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(help_text='Описание библиотеки', null=True, verbose_name='Описание')),
                ('title_2', models.CharField(max_length=255, verbose_name='Заголовок о мероприятиях')),
                ('title_2_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок о мероприятиях')),
                ('title_2_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок о мероприятиях')),
            ],
            options={
                'verbose_name': 'Объявление о мероприятиях',
                'verbose_name_plural': 'Объявления о мероприятиях',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Объявление о мероприятиях', max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(help_text='Объявление о мероприятиях', max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(help_text='Объявление о мероприятиях', max_length=255, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание мероприятия')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание мероприятия')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание мероприятия')),
                ('image', models.ImageField(upload_to='afisha/', verbose_name='Изображение к мероприятию')),
                ('information', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация')),
                ('information_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация')),
                ('information_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Общая информация')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на "подробнее')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
