# Generated by Django 4.2.7 on 2025-06-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afisha',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='afisha/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='afisha/', verbose_name='Изображение к мероприятию'),
        ),
    ]
