# Generated by Django 4.2.7 on 2025-07-07 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_alter_afisha_image_alter_events_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afisha',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Объявление о мероприятиях', 'verbose_name_plural': 'Объявления о мероприятиях'},
        ),
        migrations.AlterField(
            model_name='afisha',
            name='title_2',
            field=ckeditor.fields.RichTextField(verbose_name='Заголовок о мероприятиях'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='title_2_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок о мероприятиях'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='title_2_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Заголовок о мероприятиях'),
        ),
    ]
