# Generated by Django 4.2.7 on 2025-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_alter_afisha_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afisha',
            name='title_2',
            field=models.TextField(verbose_name='Заголовок о мероприятиях'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='title_2_ky',
            field=models.TextField(null=True, verbose_name='Заголовок о мероприятиях'),
        ),
        migrations.AlterField(
            model_name='afisha',
            name='title_2_ru',
            field=models.TextField(null=True, verbose_name='Заголовок о мероприятиях'),
        ),
    ]
