# Generated by Django 4.2.7 on 2025-07-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0004_alter_afisha_title_2_alter_afisha_title_2_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afisha',
            options={'verbose_name': 'Страница мероприятие', 'verbose_name_plural': 'Страница мероприятия'},
        ),
        migrations.RemoveField(
            model_name='events',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='events',
            name='information_ky',
        ),
        migrations.RemoveField(
            model_name='events',
            name='information_ru',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='events',
            name='title_ru',
        ),
    ]
