# Generated by Django 4.2.7 on 2025-07-07 09:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('author_ru', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('author_ky', models.CharField(max_length=255, null=True, verbose_name='Автор')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='book_arrival_images/', verbose_name='Изображение')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('populars', models.BooleanField(blank=True, null=True, verbose_name='Популярное')),
            ],
            options={
                'verbose_name': 'Прибытие книги',
                'verbose_name_plural': 'Прибытие книг',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_feature', models.CharField(max_length=255, verbose_name='Особенность')),
                ('special_feature_ru', models.CharField(max_length=255, null=True, verbose_name='Особенность')),
                ('special_feature_ky', models.CharField(max_length=255, null=True, verbose_name='Особенность')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('note_ru', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('note_ky', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('popular', models.BooleanField(blank=True, null=True, verbose_name='Популярное')),
                ('read_count', models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Каталог книги',
                'verbose_name_plural': 'Каталоги книг',
            },
        ),
        migrations.CreateModel(
            name='DailyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок дневных новостей')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок дневных новостей')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок дневных новостей')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание дневных новостей')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание дневных новостей')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание дневных новостей')),
                ('detailed_description', ckeditor.fields.RichTextField(verbose_name='Подробное описание')),
                ('detailed_description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Подробное описание')),
                ('detailed_description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Подробное описание')),
                ('image', models.ImageField(upload_to='daily-news-image/', verbose_name='Изображение')),
                ('date', ckeditor.fields.RichTextField(verbose_name='Дата и Время')),
                ('date_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Дата и Время')),
                ('date_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Дата и Время')),
            ],
            options={
                'verbose_name': 'Дневную новость',
                'verbose_name_plural': 'Дневные новости',
            },
        ),
        migrations.CreateModel(
            name='EventsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок мероприятия')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок мероприятия')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок мероприятия')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание мероприятия')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание мероприятия')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание мероприятия')),
                ('detailed_description', ckeditor.fields.RichTextField(verbose_name='Подробное описание')),
                ('detailed_description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Подробное описание')),
                ('detailed_description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Подробное описание')),
                ('image', models.ImageField(upload_to='events-image/', verbose_name='Изображение')),
                ('time', models.CharField(max_length=255, verbose_name='Время проведения мероприятия')),
                ('time_ru', models.CharField(max_length=255, null=True, verbose_name='Время проведения мероприятия')),
                ('time_ky', models.CharField(max_length=255, null=True, verbose_name='Время проведения мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('coverage_period', models.CharField(max_length=250, verbose_name='Период охвата')),
                ('coverage_period_ru', models.CharField(max_length=250, null=True, verbose_name='Период охвата')),
                ('coverage_period_ky', models.CharField(max_length=250, null=True, verbose_name='Период охвата')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='media_coverage_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Освещение в СМИ',
                'verbose_name_plural': 'Освещения в СМИ',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы "Новости"')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы "Новости"')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы "Новости"')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание библиотеки')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание библиотеки')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание библиотеки')),
                ('left_image', models.ImageField(upload_to='left-image/', verbose_name='Левое изображение')),
                ('middle_image', models.ImageField(upload_to='middle-image/', verbose_name='среднее изображение')),
                ('dextral_image', models.ImageField(upload_to='dextral-image/', verbose_name='Правое изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
