# Generated by Django 4.2.7 on 2025-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_catalog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='author',
            field=models.CharField(default=1, max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
