# Generated by Django 4.2.7 on 2025-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_catalog_author_catalog_title_ky_catalog_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='author_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
    ]
