# Generated by Django 4.2.7 on 2025-07-07 13:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_catalog_author_ky_catalog_author_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsnews',
            name='time',
            field=ckeditor.fields.RichTextField(verbose_name='Время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventsnews',
            name='time_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventsnews',
            name='time_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Время проведения мероприятия'),
        ),
    ]
