# Generated by Django 4.2.7 on 2025-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_eventsnews_time_alter_eventsnews_time_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsnews',
            name='time',
            field=models.TextField(verbose_name='Время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventsnews',
            name='time_ky',
            field=models.TextField(null=True, verbose_name='Время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventsnews',
            name='time_ru',
            field=models.TextField(null=True, verbose_name='Время проведения мероприятия'),
        ),
    ]
