# Generated by Django 4.2.7 on 2025-05-27 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('el_library', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readbook',
            name='cabinet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='read_books', to='users.usercabinet'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='readbook',
            unique_together={('cabinet', 'book')},
        ),
        migrations.RemoveField(
            model_name='readbook',
            name='user',
        ),
    ]
