# Generated by Django 4.2.7 on 2025-06-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_readbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='readbooks/files/', verbose_name='Файл для скачивания'),
        ),
        migrations.AddField(
            model_name='readbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='readbooks/images/', verbose_name='Изображение'),
        ),
    ]
