# Generated by Django 4.2.7 on 2025-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureandlibraries',
            name='image_ky',
            field=models.ImageField(null=True, upload_to='StructureAndLibraries-image/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='structureandlibraries',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='StructureAndLibraries-image/', verbose_name='Изображение'),
        ),
    ]
